import type { Locale } from "@/lib/dictionary";

const EXACT: Record<string, Record<Locale, string>> = {
  "En sourcing": { en: "Sourcing", fr: "En sourcing" },
  "En due diligence": { en: "Due diligence", fr: "En due diligence" },
  "En IC": { en: "IC", fr: "En IC" },
  "En négociation": { en: "Negotiation", fr: "En négociation" },
  Closed: { en: "Closed", fr: "Closed" },
  Qualification: { en: "Qualification", fr: "Qualification" },
  "Portfolio monitoring": { en: "Portfolio monitoring", fr: "Portfolio monitoring" },
  "Discussion active": { en: "Active discussion", fr: "Discussion active" },
  "Due diligence / commercial": { en: "Due diligence / commercial", fr: "Due diligence / commercial" },
  "Documentation incomplète": { en: "Incomplete documentation", fr: "Documentation incomplète" },
  "Term sheet reçue": { en: "Term sheet received", fr: "Term sheet reçue" },
  "Comité d'investissement à préparer": { en: "Investment committee to prepare", fr: "Comité d'investissement à préparer" },
  "Due diligence en cours": { en: "Due diligence in progress", fr: "Due diligence en cours" },
  "Négociation / term sheet": { en: "Negotiation / term sheet", fr: "Négociation / term sheet" },
  "Dossier incomplet": { en: "Incomplete file", fr: "Dossier incomplet" },
  "Nouveau lead": { en: "New lead", fr: "Nouveau lead" },
  "Valider proposition commerciale": { en: "Validate commercial proposal", fr: "Valider proposition commerciale" },
  "Préparer comité d'investissement": { en: "Prepare investment committee", fr: "Préparer comité d'investissement" },
  "Organiser call avec le CEO": { en: "Schedule a CEO call", fr: "Organiser call avec le CEO" },
  "Compléter le dossier (Drive)": { en: "Complete the file (Drive)", fr: "Compléter le dossier (Drive)" },
  "Suivre le dossier": { en: "Follow the file", fr: "Suivre le dossier" },
  "À planifier": { en: "To schedule", fr: "À planifier" },
  "En cours": { en: "In progress", fr: "En cours" },
  "ARR signé": { en: "Signed ARR", fr: "ARR signé" },
  "non renseigné": { en: "not on file", fr: "non renseigné" },
  "Dernière interaction": { en: "Last interaction", fr: "Dernière interaction" },
  "Situation actuelle": { en: "Current situation", fr: "Situation actuelle" },
  Activité: { en: "Activity", fr: "Activité" },
  Pays: { en: "Country", fr: "Pays" },
  Stade: { en: "Stage", fr: "Stade" },
  Thèse: { en: "Thesis", fr: "Thèse" },
  "Progression commerciale": { en: "Commercial progress", fr: "Progression commerciale" },
  "Références clients": { en: "Client references", fr: "Références clients" },
  "Date d'entrée": { en: "Date in", fr: "Date d'entrée" },
  "Financement recherché": { en: "Funding sought", fr: "Financement recherché" },
  "Valorisation recherchée": { en: "Target valuation", fr: "Valorisation recherchée" },
  Investisseurs: { en: "Investors", fr: "Investisseurs" },
  "Site web": { en: "Website", fr: "Site web" },
  Investi: { en: "Invested", fr: "Investi" },
  Valorisation: { en: "Valuation", fr: "Valorisation" },
  Secteur: { en: "Sector", fr: "Secteur" },
  Instrument: { en: "Instrument", fr: "Instrument" },
  Investissement: { en: "Investment", fr: "Investissement" },
  "Mise à jour dossier": { en: "File updated", fr: "Mise à jour dossier" },
  "Champs CRM actualisés": { en: "CRM fields updated", fr: "Champs CRM actualisés" },
  "Screening IA": { en: "AI screening", fr: "Screening IA" },
  "Score enregistré": { en: "Score recorded", fr: "Score enregistré" },
  "Entrée pipeline": { en: "Entered pipeline", fr: "Entrée pipeline" },
  "Source interne": { en: "Internal source", fr: "Source interne" },
  "Compléter le dossier fondateur": { en: "Complete the founder file", fr: "Compléter le dossier fondateur" },
  "Préparer note IC": { en: "Prepare IC memo", fr: "Préparer note IC" },
  "Documents ajoutés": { en: "Documents added", fr: "Documents ajoutés" },
  "Tâche en retard": { en: "Overdue task", fr: "Tâche en retard" },
  "À faire": { en: "To do", fr: "À faire" },
  "À valider": { en: "To validate", fr: "À valider" },
  "À décider": { en: "To decide", fr: "À décider" },
  Bloquée: { en: "Blocked", fr: "Bloquée" },
  Bloquées: { en: "Blocked", fr: "Bloquées" },
  Haute: { en: "High", fr: "Haute" },
  Moyenne: { en: "Medium", fr: "Moyenne" },
  Basse: { en: "Low", fr: "Basse" },
  Fondateur: { en: "Founder", fr: "Fondateur" },
  Investisseur: { en: "Investor", fr: "Investisseur" },
  Partenaire: { en: "Partner", fr: "Partenaire" },
  "Call fondateur": { en: "Founder call", fr: "Call fondateur" },
  "Suivi portefeuille": { en: "Portfolio follow-up", fr: "Suivi portefeuille" },
  "Due diligence": { en: "Due diligence", fr: "Due diligence" },
  "Comité d'investissement": { en: "Investment committee", fr: "Comité d'investissement" },
  "Réunion interne": { en: "Internal meeting", fr: "Réunion interne" },
  Autre: { en: "Other", fr: "Autre" },
  "Non assigné": { en: "Unassigned", fr: "Non assigné" },
  Participation: { en: "Holding", fr: "Participation" },
  Actif: { en: "Active", fr: "Actif" },
  Startup: { en: "Startup", fr: "Startup" },
  "Dossier pipeline": { en: "Pipeline file", fr: "Dossier pipeline" },
  "Valider le montant et les conditions": { en: "Validate amount and terms", fr: "Valider le montant et les conditions" },
};

const PREFIX: [string, Record<Locale, string>][] = [
  ["Activité récente", { en: "Recent activity", fr: "Activité récente" }],
  ["Ticket / levée", { en: "Ticket / round", fr: "Ticket / levée" }],
];

export function localizePhrase(locale: Locale, raw: string | null | undefined): string {
  if (!raw) return "";
  const exact = EXACT[raw];
  if (exact) return exact[locale];
  for (const [prefix, pair] of PREFIX) {
    if (raw.startsWith(prefix)) return pair[locale] + raw.slice(prefix.length);
  }
  return raw;
}
