/** Fund thesis — versioned config, not frontend hard-codes. */
export const THESIS_VERSION = "2026.09";

export const THESIS = {
  coreSectors: ["Fintech", "InsurTech", "Cybertech"],
  opportunisticSectors: [
    "DevTools",
    "Enterprise SaaS",
    "B2B SaaS",
    "HRTech",
    "LegalTech",
    "PropTech",
    "AI Infrastructure",
    "B2B software",
  ],
  aiKeywords: [
    "ai-native",
    "ai native",
    "agent",
    "agentic",
    "generative ai",
    "genai",
    "llm",
    "large language model",
    "nlp",
    "natural language",
    "computer vision",
    "machine learning",
    "predictive",
    "ml model",
    "ai infrastructure",
    "intelligence artificielle",
    "apprentissage automatique",
  ],
  geographyPriority: ["Morocco", "Europe", "MENA", "US"] as const,
  priorityGeographies: [
    "Morocco",
    "Maroc",
    "Casablanca",
    "Rabat",
    "Marrakech",
    "Agadir",
    "United Kingdom",
    "UK",
    "London",
    "France",
    "Paris",
    "Germany",
    "Berlin",
    "Netherlands",
    "Amsterdam",
    "Sweden",
    "Estonia",
    "Tunisia",
    "Tunisie",
    "Egypt",
    "UAE",
    "Saudi Arabia",
    "United States",
    "USA",
    "San Francisco",
    "New York",
  ],
  allowedRounds: [
    "pre-seed",
    "preseed",
    "pre seed",
    "seed",
    "seed+",
    "pre-series a",
    "pre series a",
    "bridge",
    "safe",
    "convertible",
  ],
  maxCumulativeRaisedUsd: 4_000_000,
} as const;
